<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Kernel\XFramework.Core\XFramework.Core.csproj" />
        <ProjectReference Include="..\..\..\Kernel\XFramework.SourceGenerators\XFramework.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Messaging.Core\Messaging.Core.csproj" />
        <ProjectReference Include="..\Messaging.Domain.Shared\Messaging.Domain.Shared.csproj" />
        <ProjectReference Include="..\Messaging.Integration\Messaging.Integration.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="HostedService\" />
    </ItemGroup>

    <ItemGroup>
        <!-- OpenTelemetry Core -->
        <PackageReference Include="OpenTelemetry" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
        
        <!-- OpenTelemetry Instrumentation -->
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.12" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc9.14" />
        
        <!-- OpenTelemetry Exporters -->
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
    </ItemGroup>

</Project>

