<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazor-State" />
        <PackageReference Include="Blazored.LocalStorage" />
        <PackageReference Include="Blazored.SessionStorage" />
        <PackageReference Include="BlazorTransitionableRoute" />
        <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Analyzers" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="Reshiru.Blazor.IndexedDB.Framework" />
        <PackageReference Include="TG.Blazor.IndexedDB" />
        <PackageReference Include="PPioli.FluentValidation.Blazor" />
        <PackageReference Include="BlazorDownloadFile" />
        <PackageReference Include="Toolbelt.Blazor.ViewTransition" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Components\Modals\" />
      <Folder Include="Core\Features\Base" />
      <Folder Include="Core\WebAssemblyExtensions\" />
      <Folder Include="Entity\Models\Responses" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Infrastructure\XFramework.Integration\XFramework.Integration.csproj" />
      <ProjectReference Include="..\XFramework.IdentityServer\IdentityServer.Integration\IdentityServer.Integration.csproj" />
      <ProjectReference Include="..\XFramework.Wallets\Wallets.Integration\Wallets.Integration.csproj" />
      <ProjectReference Include="..\XFramework.Messaging\Messaging.Integration\Messaging.Integration.csproj" />
      <ProjectReference Include="..\XFramework.Inventario\Inventario.Domain.Shared\Inventario.Domain.Shared.csproj" />
    </ItemGroup>

</Project>
