<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\SourceGenerators\XFramework.SourceGenerators\XFramework.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <!-- Core and Domain -->
        <ProjectReference Include="..\..\..\Kernel\XFramework.Core\XFramework.Core.csproj" />
        <ProjectReference Include="..\..\..\Kernel\XFramework.Domain\XFramework.Domain.csproj" />
        
        <!-- Infrastructure -->
        <ProjectReference Include="..\..\..\Infrastructure\XFramework.Integration\XFramework.Integration.csproj" />
        
        <ProjectReference Include="..\..\XFramework.Notifications\Notifications.Integration\Notifications.Integration.csproj" />
        <ProjectReference Include="..\..\XFramework.Storage\Storage.Integration\Storage.Integration.csproj" />
        
        <!-- Domain Shared (contracts and DTOs) -->
        <ProjectReference Include="..\Communications.Domain.Shared\Communications.Domain.Shared.csproj" />
        <ProjectReference Include="..\..\XFramework.Notifications\Notifications.Domain.Shared\Notifications.Domain.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Validation -->
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        
        <!-- OpenTelemetry Core -->
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        
        <!-- OpenTelemetry Instrumentation -->
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" />
        
        <!-- OpenTelemetry Exporters -->
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    </ItemGroup>

</Project>
