using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XFramework.SourceGenerators;

/// <summary>
/// Source generator that collects entity types marked with [GenerateEndpoints] and generates
/// a static registry for DataContext entity allowlisting. The generated code has no external
/// dependencies — it returns a dictionary of (name → Type) that the StreamFlow server-side
/// QueryExecutionService consumes at startup.
/// </summary>
[Generator]
public class DataContextRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetEntityInfo(ctx))
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Right!, spc));
    }

    private static EntityRegistrationInfo? GetEntityInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        foreach (var attributeData in classSymbol.GetAttributes())
        {
            var attributeClass = attributeData.AttributeClass;
            if (attributeClass == null)
                continue;

            if (attributeClass.Name != "GenerateEndpointsAttribute" &&
                attributeClass.ToDisplayString() != "XFramework.Core.Attributes.GenerateEndpointsAttribute")
                continue;

            return new EntityRegistrationInfo
            {
                ClassName = classSymbol.Name,
                FullyQualifiedName = classSymbol.ToDisplayString()
            };
        }

        return null;
    }

    private static void Execute(ImmutableArray<EntityRegistrationInfo?> entities, SourceProductionContext context)
    {
        var validEntities = entities
            .Where(e => e is not null)
            .Select(e => e!)
            .GroupBy(e => e.FullyQualifiedName)
            .Select(g => g.First())
            .OrderBy(e => e.ClassName)
            .ToList();

        if (validEntities.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace XFramework.Core.DataContext;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated entity type registry for DataContext.");
        sb.AppendLine("/// Call GetDataContextEntityTypes() to get the allowlist for QueryExecutionService.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class DataContextEntityRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static Dictionary<string, Type> GetDataContextEntityTypes() => new()");
        sb.AppendLine("    {");

        foreach (var entity in validEntities)
        {
            sb.AppendLine($"        [\"{entity.ClassName}\"] = typeof({entity.FullyQualifiedName}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("DataContextEntityRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class EntityRegistrationInfo
    {
        public string ClassName { get; set; } = "";
        public string FullyQualifiedName { get; set; } = "";
    }
}
