using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XFramework.SourceGenerators;

/// <summary>
/// Source generator that creates service layer code for entities marked with [GenerateEndpoints].
/// Implements tenant isolation and navigation loading support.
/// Uses the incremental generator API for better performance.
/// </summary>
[Generator]
public class EntityServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register syntax provider to find classes with GenerateEndpoints attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // Register source output
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        // Check if it's a class with attributes
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static ServiceInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        // Get the symbol for the class
        if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        // Look for GenerateEndpointsAttribute
        foreach (var attributeData in classSymbol.GetAttributes())
        {
            var attributeClass = attributeData.AttributeClass;
            if (attributeClass == null)
                continue;

            // Check both short name and full name to be more robust
            if (attributeClass.Name != "GenerateEndpointsAttribute" &&
                attributeClass.ToDisplayString() != "XFramework.Core.Attributes.GenerateEndpointsAttribute")
                continue;

            // Extract attribute properties
            var type = GetEnumValue<int>(attributeData, "Type", 3); // Default Both = 3
            var actions = GetEnumValue<int>(attributeData, "Actions", 31); // Default All = 31

            // Only generate service if Type is Service (1) or Both (3)
            if (type != 1 && type != 3)
                return null;

            // Check if entity implements IHasTenantId
            var hasTenantId = classSymbol.AllInterfaces.Any(i => i.Name == "IHasTenantId");

            return new ServiceInfo
            {
                ClassName = classSymbol.Name,
                Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
                Actions = actions,
                HasTenantId = hasTenantId
            };
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ServiceInfo> entities, SourceProductionContext context)
    {
        if (entities.IsDefaultOrEmpty)
            return;

        foreach (var entity in entities)
        {
            if (entity == null)
                continue;

            // Generate the service class
            var source = GenerateServiceCode(entity);
            context.AddSource($"{entity.ClassName}Service.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateServiceCode(ServiceInfo entity)
    {
        var entityName = entity.ClassName;
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using XFramework.Core.Patterns;");
        sb.AppendLine("using XFramework.Core.Services.Caching;");
        sb.AppendLine("using XFramework.Core.Services;");
        sb.AppendLine("using XFramework.Domain.Shared.Contracts.Base;");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"namespace {entity.Namespace}");
            sb.AppendLine("{");
        }

        // Service interface
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Auto-generated service interface for {entityName} entity.");
        sb.AppendLine($"    /// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public partial interface I{entityName}Service");
        sb.AppendLine("    {");
        
        if ((entity.Actions & 1) != 0) // Create
            sb.AppendLine($"        Task<Result<{entityName}>> CreateAsync(Create{entityName}Request request, CancellationToken ct = default);");
        if ((entity.Actions & 2) != 0) // Get
            sb.AppendLine($"        Task<Result<{entityName}>> GetByIdAsync(Guid id, bool includeNavigations = false, int navigationDepth = 1, CancellationToken ct = default);");
        if ((entity.Actions & 4) != 0) // GetList
            sb.AppendLine($"        Task<Result<List<{entityName}>>> GetListAsync(Get{entityName}ListRequest request, bool includeNavigations = false, int navigationDepth = 1, CancellationToken ct = default);");
        if ((entity.Actions & 8) != 0) // Update
            sb.AppendLine($"        Task<Result<{entityName}>> UpdateAsync(Guid id, Update{entityName}Request request, CancellationToken ct = default);");
        if ((entity.Actions & 16) != 0) // Delete
            sb.AppendLine($"        Task<Result> DeleteAsync(Guid id, CancellationToken ct = default);");
        
        sb.AppendLine("    }");
        sb.AppendLine();

        // Service implementation
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Auto-generated service implementation for {entityName} entity.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public partial class {entityName}Service : I{entityName}Service");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly DbContext _context;");
        sb.AppendLine("        private readonly ICacheService _cacheService;");
        if (entity.HasTenantId)
        {
            sb.AppendLine("        private readonly ITenantService _tenantService;");
        }
        sb.AppendLine();

        // Constructor
        sb.AppendLine($"        public {entityName}Service(");
        sb.AppendLine("            DbContext context,");
        if (entity.HasTenantId)
        {
            sb.AppendLine("            ICacheService cacheService,");
            sb.AppendLine("            ITenantService tenantService)");
        }
        else
        {
            sb.AppendLine("            ICacheService cacheService)");
        }
        sb.AppendLine("        {");
        sb.AppendLine("            _context = context;");
        sb.AppendLine("            _cacheService = cacheService;");
        if (entity.HasTenantId)
        {
            sb.AppendLine("            _tenantService = tenantService;");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // Tenant helper method
        if (entity.HasTenantId)
        {
            sb.AppendLine("        private async Task<Guid> GetCurrentTenantIdAsync()");
            sb.AppendLine("        {");
            sb.AppendLine("            var tenantId = await _tenantService.GetCurrentTenantIdAsync();");
            sb.AppendLine("            if (tenantId == Guid.Empty)");
            sb.AppendLine("                throw new UnauthorizedAccessException(\"No valid tenant context found\");");
            sb.AppendLine("            return tenantId;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Generate CRUD methods
        if ((entity.Actions & 1) != 0) // Create
        {
            GenerateCreateMethod(sb, entityName, entity.HasTenantId);
        }

        if ((entity.Actions & 2) != 0) // Get
        {
            GenerateGetByIdMethod(sb, entityName, entity.HasTenantId);
        }

        if ((entity.Actions & 4) != 0) // GetList
        {
            GenerateGetListMethod(sb, entityName, entity.HasTenantId);
        }

        if ((entity.Actions & 8) != 0) // Update
        {
            GenerateUpdateMethod(sb, entityName, entity.HasTenantId);
        }

        if ((entity.Actions & 16) != 0) // Delete
        {
            GenerateDeleteMethod(sb, entityName, entity.HasTenantId);
        }

        // Navigation loading helper method
        GenerateIncludeNavigationsMethod(sb, entityName);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine("}");
        }

        sb.AppendLine();
        sb.AppendLine("#pragma warning restore CS1591");

        return sb.ToString();
    }

    private static void GenerateCreateMethod(StringBuilder sb, string entityName, bool hasTenantId)
    {
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public virtual async Task<Result<{entityName}>> CreateAsync(Create{entityName}Request request, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                // Map request to entity - this partial method can be implemented in a separate file");
        sb.AppendLine($"                var entity = MapCreateRequestToEntity(request);");
        sb.AppendLine();
        if (hasTenantId)
        {
            sb.AppendLine("                var tenantId = await GetCurrentTenantIdAsync();");
            sb.AppendLine("                ((IHasTenantId)entity).TenantId = tenantId;");
            sb.AppendLine();
        }
        sb.AppendLine($"                _context.Set<{entityName}>().Add(entity);");
        sb.AppendLine("                await _context.SaveChangesAsync(ct);");
        sb.AppendLine($"                return Result<{entityName}>.Success(entity, 201, \"{entityName} created successfully\");");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return Result<{entityName}>.Failure($\"Failed to create {entityName}: {{ex.Message}}\", 500);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps a Create{entityName}Request to a {entityName} entity.");
        sb.AppendLine($"        /// Implement this partial method in a separate file to provide mapping logic.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        protected virtual partial {entityName} MapCreateRequestToEntity(Create{entityName}Request request);");
        sb.AppendLine();
    }

    private static void GenerateGetByIdMethod(StringBuilder sb, string entityName, bool hasTenantId)
    {
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public virtual async Task<Result<{entityName}>> GetByIdAsync(Guid id, bool includeNavigations = false, int navigationDepth = 1, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var query = _context.Set<{entityName}>().AsNoTracking();");
        sb.AppendLine();
        if (hasTenantId)
        {
            sb.AppendLine("                var tenantId = await GetCurrentTenantIdAsync();");
            sb.AppendLine("                query = query.Where(e => ((IHasTenantId)e).TenantId == tenantId);");
            sb.AppendLine();
        }
        sb.AppendLine("                if (includeNavigations)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    query = IncludeNavigations(query, typeof({entityName}), navigationDepth);");
        sb.AppendLine("                    query = query.AsSplitQuery();");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                var entity = await query.FirstOrDefaultAsync(e => e.Id == id, ct);");
        sb.AppendLine("                if (entity == null)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return Result<{entityName}>.NotFound($\"{entityName} with ID {{id}} not found\");");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine($"                return Result<{entityName}>.Success(entity);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return Result<{entityName}>.Failure($\"Failed to retrieve {entityName}: {{ex.Message}}\", 500);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateGetListMethod(StringBuilder sb, string entityName, bool hasTenantId)
    {
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public virtual async Task<Result<List<{entityName}>>> GetListAsync(Get{entityName}ListRequest request, bool includeNavigations = false, int navigationDepth = 1, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var query = _context.Set<{entityName}>().AsNoTracking();");
        sb.AppendLine();
        if (hasTenantId)
        {
            sb.AppendLine("                var tenantId = await GetCurrentTenantIdAsync();");
            sb.AppendLine("                query = query.Where(e => ((IHasTenantId)e).TenantId == tenantId);");
            sb.AppendLine();
        }
        sb.AppendLine("                // Apply custom filters - override ApplyFilters to customize");
        sb.AppendLine("                query = ApplyFilters(query, request);");
        sb.AppendLine();
        sb.AppendLine("                if (includeNavigations)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    query = IncludeNavigations(query, typeof({entityName}), navigationDepth);");
        sb.AppendLine("                    query = query.AsSplitQuery();");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                // Apply pagination");
        sb.AppendLine("                var skip = (request.Page - 1) * request.PageSize;");
        sb.AppendLine("                var entities = await query.Skip(skip).Take(request.PageSize).ToListAsync(ct);");
        sb.AppendLine();
        sb.AppendLine($"                return Result<List<{entityName}>>.Success(entities);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return Result<List<{entityName}>>.Failure($\"Failed to retrieve {entityName} list: {{ex.Message}}\", 500);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Applies filters to the query based on the request.");
        sb.AppendLine($"        /// Implement this partial method in a separate file to add custom filtering logic.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        protected virtual partial IQueryable<{entityName}> ApplyFilters(IQueryable<{entityName}> query, Get{entityName}ListRequest request);");
        sb.AppendLine();
    }

    private static void GenerateUpdateMethod(StringBuilder sb, string entityName, bool hasTenantId)
    {
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public virtual async Task<Result<{entityName}>> UpdateAsync(Guid id, Update{entityName}Request request, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var query = _context.Set<{entityName}>();");
        if (hasTenantId)
        {
            sb.AppendLine("                var tenantId = await GetCurrentTenantIdAsync();");
            sb.AppendLine("                var entity = await query.FirstOrDefaultAsync(e => e.Id == id && ((IHasTenantId)e).TenantId == tenantId, ct);");
        }
        else
        {
            sb.AppendLine("                var entity = await query.FirstOrDefaultAsync(e => e.Id == id, ct);");
        }
        sb.AppendLine("                if (entity == null)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return Result<{entityName}>.NotFound($\"{entityName} with ID {{id}} not found\");");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                // Map request to entity - this partial method can be implemented in a separate file");
        sb.AppendLine("                MapUpdateRequestToEntity(request, entity);");
        sb.AppendLine();
        sb.AppendLine("                await _context.SaveChangesAsync(ct);");
        sb.AppendLine($"                return Result<{entityName}>.Success(entity, \"{entityName} updated successfully\");");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return Result<{entityName}>.Failure($\"Failed to update {entityName}: {{ex.Message}}\", 500);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps an Update{entityName}Request to an existing {entityName} entity.");
        sb.AppendLine($"        /// Implement this partial method in a separate file to provide mapping logic.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        protected virtual partial void MapUpdateRequestToEntity(Update{entityName}Request request, {entityName} entity);");
        sb.AppendLine();
    }

    private static void GenerateDeleteMethod(StringBuilder sb, string entityName, bool hasTenantId)
    {
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine("        public virtual async Task<Result> DeleteAsync(Guid id, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var query = _context.Set<{entityName}>();");
        if (hasTenantId)
        {
            sb.AppendLine("                var tenantId = await GetCurrentTenantIdAsync();");
            sb.AppendLine("                var entity = await query.FirstOrDefaultAsync(e => e.Id == id && ((IHasTenantId)e).TenantId == tenantId, ct);");
        }
        else
        {
            sb.AppendLine("                var entity = await query.FirstOrDefaultAsync(e => e.Id == id, ct);");
        }
        sb.AppendLine("                if (entity == null)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return Result.NotFound($\"{entityName} with ID {{id}} not found\");");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine($"                _context.Set<{entityName}>().Remove(entity);");
        sb.AppendLine("                await _context.SaveChangesAsync(ct);");
        sb.AppendLine($"                return Result.Success(\"{entityName} deleted successfully\");");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return Result.Failure($\"Failed to delete {entityName}: {{ex.Message}}\", 500);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateIncludeNavigationsMethod(StringBuilder sb, string entityName)
    {
        sb.AppendLine($"        private static IQueryable<{entityName}> IncludeNavigations(IQueryable<{entityName}> query, Type entityType, int depth, HashSet<Type>? visitedTypes = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (depth <= 0) return query;");
        sb.AppendLine();
        sb.AppendLine("            visitedTypes ??= new HashSet<Type>();");
        sb.AppendLine("            if (!visitedTypes.Add(entityType)) return query; // Prevent circular references");
        sb.AppendLine();
        sb.AppendLine("            var navigationProperties = entityType.GetProperties()");
        sb.AppendLine("                .Where(p => (p.PropertyType.IsClass && p.PropertyType != typeof(string)) ||");
        sb.AppendLine("                           (p.PropertyType.IsGenericType && typeof(IEnumerable).IsAssignableFrom(p.PropertyType)));");
        sb.AppendLine();
        sb.AppendLine("            foreach (var nav in navigationProperties)");
        sb.AppendLine("            {");
        sb.AppendLine("                var navPath = nav.Name;");
        sb.AppendLine("                query = query.Include(navPath);");
        sb.AppendLine();
        sb.AppendLine("                if (depth > 1)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var navType = nav.PropertyType.IsGenericType");
        sb.AppendLine("                        ? nav.PropertyType.GetGenericArguments()[0]");
        sb.AppendLine("                        : nav.PropertyType;");
        sb.AppendLine();
        sb.AppendLine("                    if (navType.IsClass && navType != typeof(string) && !visitedTypes.Contains(navType))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        var nestedNavs = navType.GetProperties()");
        sb.AppendLine("                            .Where(p => (p.PropertyType.IsClass && p.PropertyType != typeof(string)) ||");
        sb.AppendLine("                                       (p.PropertyType.IsGenericType && typeof(IEnumerable).IsAssignableFrom(p.PropertyType)));");
        sb.AppendLine();
        sb.AppendLine("                        foreach (var nestedNav in nestedNavs)");
        sb.AppendLine("                        {");
        sb.AppendLine("                            var nestedPath = $\"{navPath}.{nestedNav.Name}\";");
        sb.AppendLine("                            query = query.Include(nestedPath);");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return query;");
        sb.AppendLine("        }");
    }

    private static T GetEnumValue<T>(AttributeData attributeData, string propertyName, T defaultValue)
    {
        foreach (var namedArg in attributeData.NamedArguments)
        {
            if (namedArg.Key == propertyName && namedArg.Value.Value != null)
            {
                return (T)namedArg.Value.Value;
            }
        }
        return defaultValue;
    }
}

internal class ServiceInfo
{
    public string ClassName { get; set; } = string.Empty;
    public string Namespace { get; set; } = string.Empty;
    public int Actions { get; set; }
    public bool HasTenantId { get; set; }
}