using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XFramework.SourceGenerators;

/// <summary>
/// Source generator that creates service interfaces and implementations for entities
/// marked with the GenerateEndpointsAttribute where Type is Service or Both.
/// </summary>
[Generator]
public class EntityServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register syntax provider to find classes with GenerateEndpoints attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // Register source output
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        // Check if it's a class with attributes
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static EntityInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        // Get the symbol for the class
        if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        // Look for GenerateEndpointsAttribute
        foreach (var attributeData in classSymbol.GetAttributes())
        {
            var attributeClass = attributeData.AttributeClass;
            if (attributeClass == null)
                continue;
                
            // Check both short name and full name to be more robust
            if (attributeClass.Name != "GenerateEndpointsAttribute" &&
                attributeClass.ToDisplayString() != "XFramework.Core.Attributes.GenerateEndpointsAttribute")
                continue;

            // Extract attribute properties
            var type = GetEnumValue<int>(attributeData, "Type", 3); // Default Both = 3
            var actions = GetEnumValue<int>(attributeData, "Actions", 31); // Default All = 31
            var routePrefix = GetStringValue(attributeData, "RoutePrefix");
            var requireAuth = GetBoolValue(attributeData, "RequireAuthorization", true);
            var cacheDuration = GetIntValue(attributeData, "CacheDurationSeconds", 300);
            var cacheKeyPrefix = GetStringValue(attributeData, "CacheKeyPrefix");
            var roles = GetStringArrayValue(attributeData, "Roles");

            // Only generate services if Type is Service (1) or Both (3)
            if (type != 1 && type != 3)
                return null;

            return new EntityInfo
            {
                ClassName = classSymbol.Name,
                Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
                Actions = actions,
                CacheDurationSeconds = cacheDuration,
                CacheKeyPrefix = cacheKeyPrefix ?? classSymbol.Name.ToLowerInvariant(),
                Properties = GetProperties(classSymbol)
            };
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<EntityInfo> entities, SourceProductionContext context)
    {
        if (entities.IsDefaultOrEmpty)
            return;

        foreach (var entity in entities)
        {
            if (entity == null)
                continue;

            // Generate the service interface and implementation
            var source = GenerateServiceSource(entity);
            context.AddSource($"{entity.ClassName}Service.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateServiceSource(EntityInfo entity)
    {
        var interfaceSource = GenerateServiceInterface(entity);
        var implementationSource = GenerateServiceImplementation(entity);

        return $$"""
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Threading;
            using System.Threading.Tasks;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.Extensions.Logging;
            using XFramework.Core.Patterns;
            using XFramework.Core.Services.Caching;

            namespace {{entity.Namespace}}
            {
            {{interfaceSource}}

            {{implementationSource}}
            }

            #pragma warning restore CS1591
            """;
    }

    private static string GenerateServiceInterface(EntityInfo entity)
    {
        var methods = new StringBuilder();
        var entityName = entity.ClassName;
        var actions = entity.Actions;

        // Create method (Actions & 1)
        if ((actions & 1) != 0)
        {
            methods.AppendLine($$"""
                    /// <summary>
                    /// Creates a new {{entityName}} entity.
                    /// </summary>
                    /// <param name="request">The request containing entity data</param>
                    /// <param name="ct">Cancellation token</param>
                    /// <returns>Result containing the created entity</returns>
                    Task<Result<{{entityName}}>> CreateAsync(Create{{entityName}}Request request, CancellationToken ct = default);

            """);
        }

        // Get method (Actions & 2)
        if ((actions & 2) != 0)
        {
            methods.AppendLine($$"""
                    /// <summary>
                    /// Retrieves a {{entityName}} entity by its ID.
                    /// </summary>
                    /// <param name="id">The entity ID</param>
                    /// <param name="ct">Cancellation token</param>
                    /// <returns>Result containing the entity if found</returns>
                    Task<Result<{{entityName}}>> GetByIdAsync(Guid id, CancellationToken ct = default);

            """);
        }

        // GetList method (Actions & 4)
        if ((actions & 4) != 0)
        {
            methods.AppendLine($$"""
                    /// <summary>
                    /// Retrieves a paginated list of {{entityName}} entities.
                    /// </summary>
                    /// <param name="request">The request containing filter and pagination parameters</param>
                    /// <param name="ct">Cancellation token</param>
                    /// <returns>Result containing the list of entities</returns>
                    Task<Result<List<{{entityName}}>>> GetListAsync(Get{{entityName}}ListRequest request, CancellationToken ct = default);

            """);
        }

        // Update method (Actions & 8)
        if ((actions & 8) != 0)
        {
            methods.AppendLine($$"""
                    /// <summary>
                    /// Updates an existing {{entityName}} entity.
                    /// </summary>
                    /// <param name="id">The entity ID</param>
                    /// <param name="request">The request containing updated entity data</param>
                    /// <param name="ct">Cancellation token</param>
                    /// <returns>Result containing the updated entity</returns>
                    Task<Result<{{entityName}}>> UpdateAsync(Guid id, Update{{entityName}}Request request, CancellationToken ct = default);

            """);
        }

        // Delete method (Actions & 16)
        if ((actions & 16) != 0)
        {
            methods.AppendLine($$"""
                    /// <summary>
                    /// Soft deletes a {{entityName}} entity by its ID.
                    /// </summary>
                    /// <param name="id">The entity ID</param>
                    /// <param name="ct">Cancellation token</param>
                    /// <returns>Result indicating success or failure</returns>
                    Task<Result<bool>> DeleteAsync(Guid id, CancellationToken ct = default);
            """);
        }

        return $$"""
            /// <summary>
            /// Service interface for {{entityName}} entity operations.
            /// </summary>
            public interface I{{entityName}}Service
            {
            {{methods}}
            }
            """;
    }

    private static string GenerateServiceImplementation(EntityInfo entity)
    {
        var entityName = entity.ClassName;
        var methods = new StringBuilder();

        // Generate CRUD methods based on actions
        if ((entity.Actions & 1) != 0)
            methods.AppendLine(GenerateCreateMethod(entity));

        if ((entity.Actions & 2) != 0)
            methods.AppendLine(GenerateGetByIdMethod(entity));

        if ((entity.Actions & 4) != 0)
            methods.AppendLine(GenerateGetListMethod(entity));

        if ((entity.Actions & 8) != 0)
            methods.AppendLine(GenerateUpdateMethod(entity));

        if ((entity.Actions & 16) != 0)
            methods.AppendLine(GenerateDeleteMethod(entity));

        return $$"""
            /// <summary>
            /// Service implementation for {{entityName}} entity operations.
            /// Generated partial class that can be extended with custom methods.
            /// </summary>
            public partial class {{entityName}}Service : I{{entityName}}Service
            {
                private readonly DbContext _dbContext;
                private readonly ICacheService _cacheService;
                private readonly ILogger<{{entityName}}Service> _logger;
                private const int CacheDurationSeconds = {{entity.CacheDurationSeconds}};

                public {{entityName}}Service(
                    DbContext dbContext,
                    ICacheService cacheService,
                    ILogger<{{entityName}}Service> logger)
                {
                    _dbContext = dbContext;
                    _cacheService = cacheService;
                    _logger = logger;
                }

            {{methods}}
            }
            """;
    }

    private static string GenerateCreateMethod(EntityInfo entity)
    {
        var entityName = entity.ClassName;
        var propertyMappings = GeneratePropertyMappings(entity, "request", "entity", excludeId: true, excludeAudit: true, forObjectInitializer: true);

        return $$"""
                /// <summary>
                /// Creates a new {{entityName}} entity.
                /// </summary>
                public virtual async Task<Result<{{entityName}}>> CreateAsync(Create{{entityName}}Request request, CancellationToken ct = default)
                {
                    try
                    {
                        var entity = new {{entityName}}
                        {
            {{propertyMappings}}
                        };

                        _dbContext.Set<{{entityName}}>().Add(entity);
                        await _dbContext.SaveChangesAsync(ct);

                        // Invalidate cache
                        await _cacheService.RemoveByPrefixAsync("{{entity.CacheKeyPrefix}}:", ct);

                        _logger.LogInformation("Created {EntityType} with ID {Id}", nameof({{entityName}}), entity.Id);

                        return Result<{{entityName}}>.Success(entity);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error creating {EntityType}", nameof({{entityName}}));
                        return Result<{{entityName}}>.Failure($"Failed to create {nameof({{entityName}})}", 500);
                    }
                }

        """;
    }

    private static string GenerateGetByIdMethod(EntityInfo entity)
    {
        var entityName = entity.ClassName;

        return $$"""
                /// <summary>
                /// Retrieves a {{entityName}} entity by its ID.
                /// </summary>
                public virtual async Task<Result<{{entityName}}>> GetByIdAsync(Guid id, CancellationToken ct = default)
                {
                    try
                    {
                        var cacheKey = $"{{entity.CacheKeyPrefix}}:{id}";

                        // Try cache first
                        var cached = await _cacheService.GetAsync<{{entityName}}>(cacheKey, ct);
                        if (cached.IsSuccess && cached.Data != null)
                            return Result<{{entityName}}>.Success(cached.Data);

                        // Query database with AsNoTracking
                        var entity = await _dbContext.Set<{{entityName}}>()
                            .AsNoTracking()
                            .FirstOrDefaultAsync(e => e.Id == id && !e.IsDeleted, ct);

                        if (entity == null)
                            return Result<{{entityName}}>.NotFound($"{nameof({{entityName}})} with ID {id} not found");

                        // Cache result
                        if (CacheDurationSeconds > 0)
                        {
                            await _cacheService.SetAsync(cacheKey, entity,
                                absoluteExpiration: TimeSpan.FromSeconds(CacheDurationSeconds),
                                cancellationToken: ct);
                        }

                        return Result<{{entityName}}>.Success(entity);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error retrieving {EntityType} {Id}", nameof({{entityName}}), id);
                        return Result<{{entityName}}>.Failure($"Failed to retrieve {nameof({{entityName}})}", 500);
                    }
                }

        """;
    }

    private static string GenerateGetListMethod(EntityInfo entity)
    {
        var entityName = entity.ClassName;

        return $$"""
                /// <summary>
                /// Retrieves a paginated list of {{entityName}} entities.
                /// </summary>
                public virtual async Task<Result<List<{{entityName}}>>> GetListAsync(Get{{entityName}}ListRequest request, CancellationToken ct = default)
                {
                    try
                    {
                        var query = _dbContext.Set<{{entityName}}>()
                            .AsNoTracking()
                            .Where(e => !e.IsDeleted);

                        // Apply pagination
                        var entities = await query
                            .Skip((request.Page - 1) * request.PageSize)
                            .Take(request.PageSize)
                            .ToListAsync(ct);

                        return Result<List<{{entityName}}>>.Success(entities);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error retrieving {EntityType} list", nameof({{entityName}}));
                        return Result<List<{{entityName}}>>.Failure($"Failed to retrieve {nameof({{entityName}})} list", 500);
                    }
                }

        """;
    }

    private static string GenerateUpdateMethod(EntityInfo entity)
    {
        var entityName = entity.ClassName;
        var propertyMappings = GeneratePropertyMappings(entity, "request", "entity", excludeId: true, excludeAudit: true);

        return $$"""
                /// <summary>
                /// Updates an existing {{entityName}} entity.
                /// </summary>
                public virtual async Task<Result<{{entityName}}>> UpdateAsync(Guid id, Update{{entityName}}Request request, CancellationToken ct = default)
                {
                    try
                    {
                        var entity = await _dbContext.Set<{{entityName}}>()
                            .FirstOrDefaultAsync(e => e.Id == id && !e.IsDeleted, ct);

                        if (entity == null)
                            return Result<{{entityName}}>.NotFound($"{nameof({{entityName}})} with ID {id} not found");

                        // Update properties
            {{propertyMappings}}

                        await _dbContext.SaveChangesAsync(ct);

                        // Invalidate cache
                        await _cacheService.RemoveAsync($"{{entity.CacheKeyPrefix}}:{id}", ct);
                        await _cacheService.RemoveByPrefixAsync("{{entity.CacheKeyPrefix}}:", ct);

                        _logger.LogInformation("Updated {EntityType} with ID {Id}", nameof({{entityName}}), id);

                        return Result<{{entityName}}>.Success(entity);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error updating {EntityType} {Id}", nameof({{entityName}}), id);
                        return Result<{{entityName}}>.Failure($"Failed to update {nameof({{entityName}})}", 500);
                    }
                }

        """;
    }

    private static string GenerateDeleteMethod(EntityInfo entity)
    {
        var entityName = entity.ClassName;

        return $$"""
                /// <summary>
                /// Soft deletes a {{entityName}} entity by its ID.
                /// </summary>
                public virtual async Task<Result<bool>> DeleteAsync(Guid id, CancellationToken ct = default)
                {
                    try
                    {
                        var entity = await _dbContext.Set<{{entityName}}>()
                            .FirstOrDefaultAsync(e => e.Id == id && !e.IsDeleted, ct);

                        if (entity == null)
                            return Result<bool>.NotFound($"{nameof({{entityName}})} with ID {id} not found");

                        entity.IsDeleted = true;
                        await _dbContext.SaveChangesAsync(ct);

                        // Invalidate cache
                        await _cacheService.RemoveAsync($"{{entity.CacheKeyPrefix}}:{id}", ct);
                        await _cacheService.RemoveByPrefixAsync("{{entity.CacheKeyPrefix}}:", ct);

                        _logger.LogInformation("Deleted {EntityType} with ID {Id}", nameof({{entityName}}), id);

                        return Result<bool>.Success(true);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error deleting {EntityType} {Id}", nameof({{entityName}}), id);
                        return Result<bool>.Failure($"Failed to delete {nameof({{entityName}})}", 500);
                    }
                }
        """;
    }

    private static string GeneratePropertyMappings(EntityInfo entity, string sourceName, string targetName, bool excludeId = false, bool excludeAudit = false, bool forObjectInitializer = false)
    {
        var mappings = new StringBuilder();
        var excludedProps = new HashSet<string> { "IsDeleted" };
        
        if (excludeId)
            excludedProps.Add("Id");
        
        if (excludeAudit)
        {
            excludedProps.Add("CreatedAt");
            excludedProps.Add("CreatedBy");
            excludedProps.Add("UpdatedAt");
            excludedProps.Add("UpdatedBy");
        }

        var properties = entity.Properties.Where(p => !excludedProps.Contains(p.Name)).ToList();
        
        for (int i = 0; i < properties.Count; i++)
        {
            var prop = properties[i];
            if (forObjectInitializer)
            {
                // For object initializer: "PropertyName = value,"
                var comma = i < properties.Count - 1 ? "," : "";
                mappings.AppendLine($"                {prop.Name} = {sourceName}.{prop.Name}{comma}");
            }
            else
            {
                // For assignment: "target.PropertyName = value;"
                mappings.AppendLine($"                {targetName}.{prop.Name} = {sourceName}.{prop.Name};");
            }
        }

        return mappings.ToString().TrimEnd();
    }

    private static List<PropertyInfo> GetProperties(INamedTypeSymbol classSymbol)
    {
        var properties = new List<PropertyInfo>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is IPropertySymbol property && 
                property.DeclaredAccessibility == Accessibility.Public &&
                !property.IsStatic)
            {
                properties.Add(new PropertyInfo
                {
                    Name = property.Name,
                    Type = property.Type.ToDisplayString()
                });
            }
        }

        return properties;
    }

    private static T GetEnumValue<T>(AttributeData attributeData, string propertyName, T defaultValue)
    {
        foreach (var namedArg in attributeData.NamedArguments)
        {
            if (namedArg.Key == propertyName && namedArg.Value.Value != null)
            {
                return (T)namedArg.Value.Value;
            }
        }
        return defaultValue;
    }

    private static int GetIntValue(AttributeData attributeData, string propertyName, int defaultValue)
    {
        return GetEnumValue<int>(attributeData, propertyName, defaultValue);
    }

    private static bool GetBoolValue(AttributeData attributeData, string propertyName, bool defaultValue)
    {
        foreach (var namedArg in attributeData.NamedArguments)
        {
            if (namedArg.Key == propertyName && namedArg.Value.Value != null)
            {
                return (bool)namedArg.Value.Value;
            }
        }
        return defaultValue;
    }

    private static string? GetStringValue(AttributeData attributeData, string propertyName)
    {
        foreach (var namedArg in attributeData.NamedArguments)
        {
            if (namedArg.Key == propertyName && namedArg.Value.Value is string value)
            {
                return value;
            }
        }
        return null;
    }

    private static string[]? GetStringArrayValue(AttributeData attributeData, string propertyName)
    {
        foreach (var namedArg in attributeData.NamedArguments)
        {
            if (namedArg.Key == propertyName && !namedArg.Value.IsNull)
            {
                var values = namedArg.Value.Values;
                return values.Select(v => v.Value?.ToString()).Where(v => v != null).ToArray()!;
            }
        }
        return null;
    }
}

internal class EntityInfo
{
    public string ClassName { get; set; } = string.Empty;
    public string Namespace { get; set; } = string.Empty;
    public int Actions { get; set; }
    public int CacheDurationSeconds { get; set; }
    public string CacheKeyPrefix { get; set; } = string.Empty;
    public List<PropertyInfo> Properties { get; set; } = new();
}

internal class PropertyInfo
{
    public string Name { get; set; } = string.Empty;
    public string Type { get; set; } = string.Empty;
}