global using System;
global using System.Collections.Generic;
global using Microsoft.Extensions.Configuration;
global using XFramework.Domain.Generic.BusinessObjects;
global using XFramework.Domain.Generic.Contracts.Responses;
global using HealthEssentials.Integration.Drivers;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using HealthEssentials.Domain.Generics.Contracts;
global using HealthEssentials.Domain.Generics.Enums;
global using HealthEssentials.Domain.Generics.Contracts.Requests;
global using HealthEssentials.Api.Extensions;
global using HealthEssentials.Api.Generators;
global using XFramework.Core.Abstractions;
global using XFramework.Core.Interfaces;
global using XFramework.Domain.Contexts;
global using XFramework.Domain.Generic.Contracts;
global using XFramework.Integration.Abstractions;

global using Unit = HealthEssentials.Domain.Generics.Contracts.Unit;
global using MetaData = HealthEssentials.Domain.Generics.Contracts.MetaData;
global using MetaDataType = HealthEssentials.Domain.Generics.Contracts.MetaDataType;
global using MetaDataTypeGroup = HealthEssentials.Domain.Generics.Contracts.MetaDataTypeGroup;
global using PharmacyTag = HealthEssentials.Domain.Generics.Contracts.PharmacyTag;