<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="BusinessObjects\" />
        <Folder Include="Enums\" />
        <Folder Include="Extensions\" />
        <Folder Include="Interfaces\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Shared\XFramework.Domain.Shared\XFramework.Domain.Shared.csproj" />
    </ItemGroup>

</Project>
