<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <AssemblyName>Messaging.Tests</AssemblyName>

        <RootNamespace>Messaging.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Messaging.Api\Messaging.Api.csproj" />
      <ProjectReference Include="..\Messaging.Integration\Messaging.Integration.csproj" />
    </ItemGroup>

</Project>
