import { test } from 'node:test';
import assert from 'node:assert/strict';
import { copyFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

// The module service worker is the one file the other tests cannot evaluate: vm runs classic
// scripts, and Node decides module format from the package it sits in. So the worker and its whole
// import graph are staged in a module package and imported for real. If the graph an actual module
// worker resolves at startup were broken - a missing file, a cycle, a top-level throw - a browser
// would register nothing and the device would lose its offline shell as well as its notifications.
const files = ['service-worker.module.js', 'service-worker.js', 'notifications.js',
    'notification-settings.js', 'notification-preview.mjs', 'encryption.mjs'];

function staged() {
    const directory = mkdtempSync(join(tmpdir(), 'yap-module-worker-'));
    mkdirSync(join(directory, 'vendor/openpgp'), { recursive: true });
    const source = new URL('../../Presentation/XFramework.Yap.Client/wwwroot/', import.meta.url);
    for (const file of files) copyFileSync(new URL(file, source), join(directory, file));
    copyFileSync(new URL('vendor/openpgp/openpgp.min.mjs', source), join(directory, 'vendor/openpgp/openpgp.min.mjs'));
    writeFileSync(join(directory, 'package.json'), '{"type":"module"}');
    // Generated by the SDK at build and at publish; the shape is all this needs.
    writeFileSync(join(directory, 'service-worker-assets.js'), "self.assetsManifest = { version: 'test', assets: [] };\n");
    return directory;
}

test('the module worker graph evaluates and wires every handler and the decryptor', async () => {
    const directory = staged();
    const handlers = {};
    globalThis.self = { addEventListener: (name, handler) => (handlers[name] = handler),
        location: new URL('https://yap.test/service-worker.module.js'), clients: {},
        registration: { showNotification: async () => {} } };
    try {
        await import(pathToFileURL(join(directory, 'service-worker.module.js')).href);
        // The shell, the media caches and the push handling all come from the classic worker file.
        assert.deepEqual(Object.keys(handlers).sort(), ['fetch', 'notificationclick', 'push']);
        assert.equal(self.assetsManifest.version, 'test', 'the published worker reads the manifest at top level');
        // import() is banned in a worker, so this has to be resolved before the first push arrives.
        assert.equal(typeof self.yapNotifications.preview, 'function');
        assert.equal(typeof self.yapNotificationSettings.preview, 'function');
    } finally {
        delete globalThis.self;
        rmSync(directory, { recursive: true, force: true });
    }
});
