<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Target .NET Standard or any .NET version that supports analyzers -->
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        </PropertyGroup>

    <ItemGroup>
        <!-- Roslyn packages to enable source generator development -->
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    </ItemGroup>

  <!--  <ItemGroup>
      <ProjectReference Include="..\..\Shared\XFramework.Domain.Shared\XFramework.Domain.Shared.csproj" />
    </ItemGroup>-->
    
</Project>
