<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <AssemblyName>Communications.Tests</AssemblyName>

        <RootNamespace>Communications.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Libraries\Bolt\Bolt.Server\Bolt.Server.csproj" />
      <ProjectReference Include="..\Communications.Api\Communications.Api.csproj" />
      <ProjectReference Include="..\Communications.Integration\Communications.Integration.csproj" />
      <ProjectReference Include="..\..\XFramework.Storage\Storage.Integration\Storage.Integration.csproj" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
